version: '3.8'
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    #image: arm64v8/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    networks:
      - grounding-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    hostname: kafka
    container_name: kafka
    image: bitnami/kafka:latest
    platform: linux/amd64
    #platform: linux/arm64
    restart: always
    ports:
      - "29092:29092"
    networks:
      - grounding-network
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://localhost:29092,INTERNAL://kafka:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    depends_on:
      - zookeeper

  kafdrop:
    hostname: kafdrop
    container_name: kafdrop
    image: obsidiandynamics/kafdrop
    restart: always
    ports:
      - "9000:9000"
    networks:
      - grounding-network
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka
      - zookeeper

networks:
  grounding-network:
    driver: bridge
